telegram_client:
  api_id: 0 # show on https://my.telegram.org/apps
  api_hash: 0 # show on https://my.telegram.org/apps
  session_name: chats_reader

forward_chat_id: -2 # single destination chat for all notifications

channels:
  - chat_id: -1
    link: "https://t.me/CypRusSale"
    allowed_words:
      - "пафос"
      - "paphos"
  - chat_id: -3
    link: "https://t.me/AnotherChannel"
    allowed_words:
      - "лимассол"
      - "limassol"
